#!/usr/bin/env ruby

require 'amqp'
require 'json'

EventMachine.run do
  connection = AMQP.connect(host: 'localhost')
  channel = AMQP::Channel.new(connection)

  timestamps_exchange = channel.fanout('chat.timestamps', durable: true, auto_delete: false)
  EventMachine.add_periodic_timer(1.0) do
    payload = {
      generation_timestamp: Time.now.utc,
      milliseconds: Time.now.utc.to_f * 1000.0
    }
    timestamps_exchange.publish(payload.to_json, type: 'message')
  end
end
