#!/usr/bin/env ruby

require 'amqp'
require 'json'

EventMachine.run do
  connection = AMQP.connect(host: 'localhost')
  channel = AMQP::Channel.new(connection)
  exchange = channel.fanout('chat.stream', durable: true, auto_delete: false)

  EventMachine.add_periodic_timer(1.0) do
    payload = {
      generation_timestamp: Time.now.utc
    }

    puts "Publishing a payload."
    exchange.publish(payload.to_json, type: 'message')
  end
end
